/* Auto-generated by genmsg_cpp for file /home/krishna/fuerte_workspace/sandbox/freezing-batman/applications/eklavya/pilot/eklavya_roboteq/srv/GetSpeed.srv */
#ifndef EKLAVYA_ROBOTEQ_SERVICE_GETSPEED_H
#define EKLAVYA_ROBOTEQ_SERVICE_GETSPEED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace eklavya_roboteq
{
template <class ContainerAllocator>
struct GetSpeedRequest_ {
  typedef GetSpeedRequest_<ContainerAllocator> Type;

  GetSpeedRequest_()
  {
  }

  GetSpeedRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetSpeedRequest
typedef  ::eklavya_roboteq::GetSpeedRequest_<std::allocator<void> > GetSpeedRequest;

typedef boost::shared_ptr< ::eklavya_roboteq::GetSpeedRequest> GetSpeedRequestPtr;
typedef boost::shared_ptr< ::eklavya_roboteq::GetSpeedRequest const> GetSpeedRequestConstPtr;


template <class ContainerAllocator>
struct GetSpeedResponse_ {
  typedef GetSpeedResponse_<ContainerAllocator> Type;

  GetSpeedResponse_()
  : left_speed(0)
  , right_speed(0)
  {
  }

  GetSpeedResponse_(const ContainerAllocator& _alloc)
  : left_speed(0)
  , right_speed(0)
  {
  }

  typedef int64_t _left_speed_type;
  int64_t left_speed;

  typedef int64_t _right_speed_type;
  int64_t right_speed;


  typedef boost::shared_ptr< ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetSpeedResponse
typedef  ::eklavya_roboteq::GetSpeedResponse_<std::allocator<void> > GetSpeedResponse;

typedef boost::shared_ptr< ::eklavya_roboteq::GetSpeedResponse> GetSpeedResponsePtr;
typedef boost::shared_ptr< ::eklavya_roboteq::GetSpeedResponse const> GetSpeedResponseConstPtr;

struct GetSpeed
{

typedef GetSpeedRequest Request;
typedef GetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetSpeed
} // namespace eklavya_roboteq

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eklavya_roboteq/GetSpeedRequest";
  }

  static const char* value(const  ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0e0c05cffc768dcd7d6b1b4e756a56bd";
  }

  static const char* value(const  ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0e0c05cffc768dcdULL;
  static const uint64_t static_value2 = 0x7d6b1b4e756a56bdULL;
};

template<class ContainerAllocator>
struct DataType< ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eklavya_roboteq/GetSpeedResponse";
  }

  static const char* value(const  ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 left_speed\n\
int64 right_speed\n\
\n\
\n\
";
  }

  static const char* value(const  ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetSpeedRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.left_speed);
    stream.next(m.right_speed);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetSpeedResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<eklavya_roboteq::GetSpeed> {
  static const char* value() 
  {
    return "0e0c05cffc768dcd7d6b1b4e756a56bd";
  }

  static const char* value(const eklavya_roboteq::GetSpeed&) { return value(); } 
};

template<>
struct DataType<eklavya_roboteq::GetSpeed> {
  static const char* value() 
  {
    return "eklavya_roboteq/GetSpeed";
  }

  static const char* value(const eklavya_roboteq::GetSpeed&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0e0c05cffc768dcd7d6b1b4e756a56bd";
  }

  static const char* value(const eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eklavya_roboteq/GetSpeed";
  }

  static const char* value(const eklavya_roboteq::GetSpeedRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0e0c05cffc768dcd7d6b1b4e756a56bd";
  }

  static const char* value(const eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "eklavya_roboteq/GetSpeed";
  }

  static const char* value(const eklavya_roboteq::GetSpeedResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // EKLAVYA_ROBOTEQ_SERVICE_GETSPEED_H

