(cl:defpackage eklavya_roboteq-srv
  (:use )
  (:export
   "SETSPEED"
   "<SETSPEED-REQUEST>"
   "SETSPEED-REQUEST"
   "<SETSPEED-RESPONSE>"
   "SETSPEED-RESPONSE"
   "GETSPEED"
   "<GETSPEED-REQUEST>"
   "GETSPEED-REQUEST"
   "<GETSPEED-RESPONSE>"
   "GETSPEED-RESPONSE"
  ))

